apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ssid-email-lookup
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ssid-email-lookup
  policy:
    semver:
      range: ">=0.1.0"
